### PR TITLE
add required drivers on Intel platform

### PR DESCRIPTION
**Pull request by jianhuilee**

### CODE REVIEW

**Review by xnox — APPROVED** [review]

**Comment by alfonsosanchezbeato** [comment]
Do all these modules need to be force-loaded? If not, maybe it will be better to wait for https://github.com/snapcore/core-initrd/pull/100 to be merged, so they could be included in the initramfs without forcing the loading.

**Comment by valentindavid** [comment]
#97 already adds  xhci-pci. Could we get it merged instead.

**Comment by jianhuilee** [comment]
Revised the patch based on #100 and #97 as suggested.

**Comment by jianhuilee** [comment]
@alfonsosanchezbeato may i ask your help to review this? thanks.

**Review by valentindavid — APPROVED** [review]

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM

**Comment by valentindavid** [comment]
xhci-pci-renesas is a dependency of xhci-pci so it was useless to add it. We should to remove it.

**Pull request merged**
