### PR TITLE
Use github actions for testing instead of travis

### PR DESCRIPTION
**Pull request by sergiocazzolato**
In this change:
 . Delete the travis configuration
 . Introduce the tests workflow to run tests through github actions
 . Use the new gce project called snapd-spread
 . Use the new spread downloaded from snapd-spread-tests bucket

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
The failure here is related to some changes @xnox made to the CLI interface for ubuntu-core-initramfs, but it at least shows that spread is running on GCE, which is more than we could say about travis unfortunately. 

LGTM, thanks for taking care of this, we should work on updating the CLI interface/fs layout that the `ubuntu-core-initramfs` command expects these days as a followup IMHO

**Comment by xnox** [comment]
> The failure here is related to some changes @xnox made to the CLI interface for ubuntu-core-initramfs, but it at least shows that spread is running on GCE, which is more than we could say about travis unfortunately.
> 
> LGTM, thanks for taking care of this, we should work on updating the CLI interface/fs layout that the `ubuntu-core-initramfs` command expects these days as a followup IMHO

Yeah, repacking script should pass `--feature main` as all features are collapsed into one when one builds an initrd, thus extracting / repacking can only be done with one feature too..... however, I don't quite understand the test then. Aren't we supposed to generate a new initrd for core-initrd tests, and _not_ reuse existing one?

**Comment by anonymouse64** [comment]
> Aren't we supposed to generate a new initrd for core-initrd tests, and not reuse existing one?

Yes, see the code that is failing where we build a new initrd:

https://github.com/snapcore/core-initrd/blob/f4a1fc6c3f6caf3a8feb92cb9685cbe25f566cf2/tests/lib/repack-kernel.sh#L110-L140

is this code doing the wrong thing? This is pretty much what we used in snapd. I am currently running a local run just adding `--feature main` to the `ubuntu-core-initramfs` args to see if that's all that's needed to fix the spread tests, but it sounds like maybe these arguments need to be adjusted entirely or rewritten ? I admit to not keeping up with all the CLI options changes to `ubuntu-core-initramfs` as my main usage of it is usually to just take an existing initrd and plop a new snap-bootstrap in it...

**Comment by anonymouse64** [comment]
Well my attempt to just add `--feature main` failed:

```
+ /home/core-initrd/tests/lib/repack-kernel.sh prepare /tmp/kernel-workdir
dracut-install: ERROR: installing '/tmp/tmptqc49evq.ubuntu-core-initramfs/kernel/usr/lib/modules/5.4.0-74-generic/modules.order' to 'usr/lib/modules/5.4.0-74-generic/modules.order'
Traceback (most recent call last):
  File "/usr/bin/ubuntu-core-initramfs", line 207, in <module>
    main()
  File "/usr/bin/ubuntu-core-initramfs", line 203, in main
    globals()[args.subcmd.replace("-", "_")](parser, args)
  File "/usr/bin/ubuntu-core-initramfs", line 63, in create_initrd
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/lib/dracut/dracut-install', '-D', '/tmp/tmptqc49evq.ubuntu-core-initramfs/main', '-r', '/tmp/tmptqc49evq.ubuntu-core-initramfs/kernel', '/tmp/tmptqc49evq.ubuntu-core-initramfs/kernel/usr/lib/modules/5.4.0-74-generic/modules.order', 'usr/lib/modules/5.4.0-74-generic/modules.order']' returned non-zero exit status 1.
```

**Comment by sil2100** [comment]
Ok, let us iterate on it on a separate PR.

**Pull request merged**
