### PR TITLE
repack-kernel.sh: when repackging kernel only the main feature is ava…

### PR DESCRIPTION
**Pull request by xnox**
repack-kernel.sh: when repackging kernel only the main feature is available

### CODE REVIEW

**Comment by xnox** [comment]
@mvo5 @anonymouse64 @sil2100 hopefully this will fix the new spread tests.

I guess the top level binary should be improved to not autoadd features that are not available from a skeleton.

**Comment by anonymouse64** [comment]
I'm curious if this works, it didn't when I tried it locally running spread tests but who knows

**Comment by xnox** [comment]
@anonymouse64 it now worked!

**Comment by anonymouse64** [comment]
nice!!! :tada:

**Pull request merged**
