### PR TITLE
extra-modules: add drivers needed in RPi5 initramfs

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**

### CODE REVIEW

**Review by Meulengracht — APPROVED** [review]
Thanks!

**Comment by valentindavid** [comment]
You should now rebase, the tests will then pass.

**Comment by alfonsosanchezbeato** [comment]
> You should now rebase, the tests will then pass.

Thanks, rebased now

**Review by valentindavid — APPROVED** [review]
That is a lot of module. But ok.

**Pull request merged**
