### PR TITLE
Rename "the-tool" and remove wrapper script

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Comment by alfonsosanchezbeato** [comment]
I see some file names in cloudimg-rootfs that are not changed in the PR:

```
features/cloudimg-rootfs/usr/lib/systemd/system/basic.target.wants/the-tool.service -> ../the-tool.service
features/cloudimg-rootfs/usr/lib/systemd/system/the-tool.service (this one also has `ExecStart=/usr/lib/the-tool`)
features/cloudimg-rootfs/usr/lib/the-tool
```

I also see some reference to `the-tool` in snapd tests, so this change would need to be coordinated with snapd codebase:

```
./vendor/gopath/src/github.com/snapcore/snapd/tests/core/basic20/task.yaml:51:    # ensure that our the-tool (and thus our snap-bootstrap ran)
./vendor/gopath/src/github.com/snapcore/snapd/tests/core/basic20/task.yaml:55:        test -e /writable/system-data/the-tool-ran
./vendor/gopath/src/github.com/snapcore/snapd/tests/lib/prepare.sh:576:        # modify the-tool to verify that our version is used when booting - this
./vendor/gopath/src/github.com/snapcore/snapd/tests/lib/prepare.sh:578:        sed -i -e 's/set -e/set -ex/' "$skeletondir/main/usr/lib/the-tool"
./vendor/gopath/src/github.com/snapcore/snapd/tests/lib/prepare.sh:580:        sed -i -e "s@/usr/lib/snapd/snap-bootstrap@beforeDate=\$(date --utc \'+%s\'); /usr/lib/snapd/snap-bootstrap@"  "$skeletondir/main/usr/lib/the-tool"
./vendor/gopath/src/github.com/snapcore/snapd/tests/lib/prepare.sh:583:            echo "if test -d /run/mnt/data/system-data; then touch /run/mnt/data/system-data/the-tool-ran; fi" 
./vendor/gopath/src/github.com/snapcore/snapd/tests/lib/prepare.sh:592:        } >> "$skeletondir/main/usr/lib/the-tool"
./vendor/gopath/src/github.com/snapcore/snapd/tests/lib/prepare.sh:595:            # add a kernel panic to the end of the-tool execution
./vendor/gopath/src/github.com/snapcore/snapd/tests/lib/prepare.sh:596:            echo "echo 'forcibly panicing'; echo c > /proc/sysrq-trigger" >> "$skeletondir/main/usr/lib/the-tool"
```

**Comment by valentindavid** [comment]
> I see some file names in cloudimg-rootfs that are not changed in the PR:

I cannot really change that until I can test it. I have asked @xnox about how to change that part.

**Comment by valentindavid** [comment]
> I also see some reference to `the-tool` in snapd tests, so this change would need to be coordinated with snapd codebase:

Yes, when they start testing core22.

I believe the files in `vendor/gopath` are downloaded by go when building snap-bootstrap. And they are not used by our tests.

**Comment by xnox** [comment]
I think doing this will help to simplify cloudimg-rootfs feature. Will try to double check all that. I think at the moment it would be easiest to test that by building this current codebase on focal (despite jammy target).

**Comment by xnox** [comment]
I am caught up in point release stuff. I think this proposal is correct and good for UC. It does regress the cloudimg-rootfs feature. Do you want me to make matching changes for the cloudimg-rootfs features and propose into this valentin's branch, and once that is merged, merge into main here?

Or would you rather merge this as is. Temporarily regress cloudimg-rootfs feature. And then it would be on me to make PR to unbreak cloudimg-rootfs.

**Comment by alfonsosanchezbeato** [comment]
> I am caught up in point release stuff. I think this proposal is correct and good for UC. It does regress the cloudimg-rootfs feature. Do you want me to make matching changes for the cloudimg-rootfs features and propose into this valentin's branch, and once that is merged, merge into main here?
> 
> Or would you rather merge this as is. Temporarily regress cloudimg-rootfs feature. And then it would be on me to make PR to unbreak cloudimg-rootfs.

I think you can propose to this branch if @valentindavid is fine with that, to avoid regressing cloudimg-rootfs. It is a nice, but non-urgent change.

**Comment by valentindavid** [comment]
I think either way. If you are busy we can merge this and get `cloudimg-rootfs`. If you have time to propose a fix for that branch, then it is fine to wait. While it is not urgent, I think it would be good to get this merged before release of uc22... and not right before.

**Review by xnox — APPROVED** [review]
Let's merge this. For cloudimg-rootfs opened a new issue.

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thanks

**Pull request merged**
