### PR TITLE
bin/ubuntu-core-initramfs: make sure the initramfs can be cross-built

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
By using the --root option.

### CODE REVIEW

**Comment by alfonsosanchezbeato** [comment]
Goes on top of https://github.com/snapcore/core-initrd/pull/225

**Comment by xnox** [comment]
Review diff is now confusing, as i think the parent branch got rewritten. Could you please rebase or merge the current development tip please?

**Comment by alfonsosanchezbeato** [comment]
@xnox rebased now

**Review by kubiko — APPROVED** [review]
LGTM
Thank you @alfonsosanchezbeato  very nice!

**Pull request merged**
